default['java']['install_flavor'] = 'oracle' 
default['java']['jdk_version'] = '8' 
default['java']['oracle']['accept_oracle_download_terms'] = true 
default['logstash']['instance_default']['basedir'] = '/opt/logstash'
default['logstash']['instance_default']['version'] = '1.5.2'
default['logstash']['instance_default']['source_url'] = 'https://download.elastic.co/logstash/logstash/logstash-1.5.2.tar.gz'
default['logstash']['instance_default']['checksum'] = '1d1805d388392a69f5049b35c176186389a7f8bf7347c4528c255edc1f9b0d6a'
default['logstash']['instance_default']['install_type'] = 'tarball'
default['logstash']['instance_default']['init_method'] = 'native'
default['logstash']['instance_default']['instance_name'] = 'processor'
default['logstash']['instance_default']['user'] = 'root'
default['logstash']['instance_default']['group'] = 'root'
default['logstash']['instance_default']['lumberjack_data_bag'] = 'lumberjack'
default['logstash']['instance_default']['plugins_version'] = '1.4.3'
default['logstash']['instance_default']['plugins_source_url'] = 'https://download.elastic.co/logstash/logstash/logstash-1.4.3.tar.gz'
default['logstash']['instance_default']['plugins_checksum'] = 'dafc5e5cb2814d0ea8da270a9b6fc57a50829ed1'
default['logstash']['instance_default']['plugins_install_type'] = 'tarball'
#default['logstash']['instance_default']['config_templates']['input_file'] = 'logstash/input_file.conf.erb'
#default['logstash']['instance_default']['config_templates']['output_kafka'] =  'logstash/output_elasticsearch.conf.erb'
default['logstash']['instance_default']['config_templates_cookbook'] = 'iaas-logservice'
#default['logstash']['instance_default']['config_templates_variables'] = {
#        request_required_acks: 1,
#        producer_type: 'async',
#        topic_id: 'logstash',
#        group_id: 'logstash-processor',
#        reset_beginning: false,
#        consumer_threads: 4,
#        queue_size: 2000,
#        rebalance_max_retries: 4,
#        rebalance_backoff_ms: 2000,
#        consumer_timeout_ms: 10000,
#        consumer_restart_on_error: true,
#        consumer_restart_sleep_ms: 500,
#        decorate_events: false,
#        fetch_message_max_bytes: 10485760,
#        es_discover_host: 'localhost',
#        es_protocol: 'http',
#        es_index_name: 'log-%{+YYYY.MM.dd}',
#        enable_stdout: false
#      }